[package]
name = "bevy_mod_aseprite"
version = "0.3.0"
edition = "2021"
description = "A plugin for using Aseprite animations in Bevy"
repository = "https://github.com/lerouxrgd/bevy_mod_aseprite"
license = "MIT OR Apache-2.0"
exclude = ["assets/"]

[dependencies]
bevy = { version = "0.9", default-features = false, features = ["render", "bevy_asset"] }
bevy_aseprite_derive = "0.2"
bevy_aseprite_reader = "0.1"

[dev-dependencies]
bevy = { version = "0.9" }
